EC-LAB SETTING FILE

Number of linked techniques : 6

EC-LAB for windows v11.50 (software)
Internet server v11.50 (firmware)
Command interpretor v11.50 (firmware)

Filename : C:\Users\HZ-7000\Documents\EC-Lab\Data\Yatsuzuka\20240517_2-140_kinetic_CA\20240517_2-140_kinetic_CA_K-2.mps

Device : SP-150e
CE vs. WE compliance from -10 V to 10 V
Electrode connection : standard
Potential control : Ewe
Ewe ctrl range : min = -1.00 V, max = 1.00 V
Safety Limits :
	Do not start on E overload
Electrode material : 
Initial state : 
Electrolyte : 
Comments : 
Electrode surface area : 0.001 cm2
Characteristic mass : 0.001 g
Equivalent Weight : 0.000 g/eq.
Density : 0.000 g/cm3
Volume (V) : 0.001 cm3
Cycle Definition : Charge/Discharge alternance
Do not turn to OCV between techniques

Technique : 1
Cyclic Voltammetry Advanced
Ei (V)              0.350               
vs.                 Ref                 
ti (h:m:s)          0:00:10.0000        
dti (s)             0.0000              
dE/dt               10.000              
dE/dt unit          mV/s                
E1 (V)              0.450               
vs.                 Ref                 
t1 (h:m:s)          0:00:0.0000         
dt1 (s)             0.1000              
Step percent        50                  
N                   10                  
E range min (V)     -1.000              
E range max (V)     1.000               
I Range             Auto                
I Range min         Unset               
I Range max         Unset               
I Range init        Unset               
Bandwidth           5                   
E2 (V)              0.350               
vs.                 Ref                 
t2 (h:m:s)          0:00:0.0000         
dt2 (s)             0.1000              
nc cycles           9                   
nr                  1                   
Reverse Scan        0                   
Ef (V)              0.000               
vs.                 Eoc                 
tf (h:m:s)          0:00:0.0000         
dtf (s)             0.1000              

Technique : 2
Potentio Electrochemical Impedance Spectroscopy
Mode                Single sine         
E (V)               0.4500              
vs.                 Ref                 
tE (h:m:s)          0:00:0.0000         
record              0                   
dI                  0.000               
unit dI             mA                  
dt (s)              0.000               
fi                  500.000             
unit fi             kHz                 
ff                  1.000               
unit ff             Hz                  
Nd                  6                   
Points              per decade          
spacing             Logarithmic         
Va (mV)             10.0                
pw                  0.10                
Na                  2                   
corr                0                   
E range min (V)     -1.000              
E range max (V)     1.000               
I Range             Auto                
Bandwidth           5                   
nc cycles           0                   
goto Ns'            0                   
nr cycles           0                   
inc. cycle          0                   

Technique : 3
Cyclic Voltammetry Advanced
Ei (V)              0.450               
vs.                 Ref                 
ti (h:m:s)          0:00:10.0000        
dti (s)             0.0000              
dE/dt               5.000               
dE/dt unit          mV/s                
E1 (V)              0.700               
vs.                 Ref                 
t1 (h:m:s)          0:00:0.0000         
dt1 (s)             0.1000              
Step percent        50                  
N                   10                  
E range min (V)     -1.000              
E range max (V)     1.000               
I Range             10 mA               
I Range min         Unset               
I Range max         Unset               
I Range init        Unset               
Bandwidth           5                   
E2 (V)              0.450               
vs.                 Ref                 
t2 (h:m:s)          0:00:0.0000         
dt2 (s)             0.1000              
nc cycles           14                  
nr                  1                   
Reverse Scan        0                   
Ef (V)              0.000               
vs.                 Eoc                 
tf (h:m:s)          0:00:0.0000         
dtf (s)             0.1000              

Technique : 4
Chronoamperometry / Chronocoulometry
Ns                  0                   1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  14                  15                  16                  17                  18                  19                  20                  21                  22                  23                  24                  25                  26                  27                  28                  29                  30                  31                  32                  33                  34                  35                  36                  37                  38                  39                  40                  41                  42                  43                  44                  45                  46                  47                  48                  49                  50                  51                  52                  53                  54                  55                  56                  57                  58                  59                  60                  61                  62                  63                  64                  65                  66                  67                  68                  69                  70                  
Ei (V)              0.000               0.010               0.020               0.030               0.040               0.050               0.060               0.070               0.080               0.090               0.100               0.110               0.120               0.130               0.140               0.150               0.160               0.170               0.180               0.190               0.200               0.210               0.220               0.230               0.240               0.250               0.260               0.270               0.280               0.290               0.300               0.310               0.320               0.330               0.340               0.350               0.360               0.370               0.380               0.390               0.400               0.410               0.420               0.430               0.440               0.450               0.460               0.470               0.480               0.490               0.500               0.510               0.520               0.530               0.540               0.550               0.560               0.570               0.580               0.590               0.600               0.610               0.620               0.630               0.640               0.650               0.660               0.670               0.680               0.690               0.700               
vs.                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 
ti (h:m:s)          0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        
Imax                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                
unit Imax           mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  
Imin                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                
unit Imin           mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  
dQM                 0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
unit dQM            mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                
record              <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 
dI                  5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               
unit dI             uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  
dQ                  0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
unit dQ             mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                
dt (s)              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              
dta (s)             0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              
E range min (V)     -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              
E range max (V)     1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               
I Range             10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               
I Range min         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range max         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range init        Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
Bandwidth           5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   
goto Ns'            0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   
nc cycles           0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   

Technique : 5
Chronoamperometry / Chronocoulometry
Ns                  0                   1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  14                  15                  16                  17                  18                  19                  20                  21                  22                  23                  24                  25                  26                  27                  28                  29                  30                  31                  32                  33                  34                  35                  36                  37                  38                  39                  40                  41                  42                  43                  44                  45                  46                  47                  48                  49                  50                  51                  52                  53                  54                  55                  56                  57                  58                  59                  60                  61                  62                  63                  64                  65                  66                  67                  68                  69                  70                  
Ei (V)              0.700               0.690               0.680               0.670               0.660               0.650               0.640               0.630               0.620               0.610               0.600               0.590               0.580               0.570               0.560               0.550               0.540               0.530               0.520               0.510               0.500               0.490               0.480               0.470               0.460               0.450               0.440               0.430               0.420               0.410               0.400               0.390               0.380               0.370               0.360               0.350               0.340               0.330               0.320               0.310               0.300               0.290               0.280               0.270               0.260               0.250               0.240               0.230               0.220               0.210               0.200               0.190               0.180               0.170               0.160               0.150               0.140               0.130               0.120               0.110               0.100               0.090               0.080               0.070               0.060               0.050               0.040               0.030               0.020               0.010               0.000               
vs.                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 
ti (h:m:s)          0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        0:00:10.0000        
Imax                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                
unit Imax           mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  
Imin                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                
unit Imin           mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  
dQM                 0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
unit dQM            mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                
record              <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 
dI                  5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               
unit dI             uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  
dQ                  0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
unit dQ             mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                
dt (s)              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              
dta (s)             0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              
E range min (V)     -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              
E range max (V)     1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               
I Range             10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               10 mA               
I Range min         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range max         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range init        Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
Bandwidth           5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   
goto Ns'            0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   
nc cycles           0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   

Technique : 6
Cyclic Voltammetry Advanced
Ei (V)              0.000               
vs.                 Ref                 
ti (h:m:s)          0:00:10.0000        
dti (s)             0.0000              
dE/dt               5.000               
dE/dt unit          mV/s                
E1 (V)              0.700               
vs.                 Ref                 
t1 (h:m:s)          0:00:0.0000         
dt1 (s)             0.1000              
Step percent        50                  
N                   10                  
E range min (V)     -1.000              
E range max (V)     1.000               
I Range             Auto                
I Range min         Unset               
I Range max         Unset               
I Range init        Unset               
Bandwidth           5                   
E2 (V)              0.000               
vs.                 Ref                 
t2 (h:m:s)          0:00:0.0000         
dt2 (s)             0.1000              
nc cycles           0                   
nr                  1                   
Reverse Scan        1                   
Ef (V)              0.350               
vs.                 Ref                 
tf (h:m:s)          0:00:0.0000         
dtf (s)             0.1000              
