EC-LAB SETTING FILE

Number of linked techniques : 2

EC-LAB for windows v11.50 (software)
Internet server v11.50 (firmware)
Command interpretor v11.50 (firmware)

Filename : C:\Users\HZ-7000\Documents\EC-Lab\Data\Yatsuzuka\20240514_2-139_kinetics_test\20240514_2-139_kinetic_test_forward_backward_2.mps

Device : SP-150e
CE vs. WE compliance from -10 V to 10 V
Electrode connection : standard
Potential control : Ewe
Ewe ctrl range : min = -1.00 V, max = 1.00 V
Safety Limits :
	Do not start on E overload
Electrode material : 
Initial state : 
Electrolyte : 
Comments : 
Electrode surface area : 0.001 cm2
Characteristic mass : 0.001 g
Equivalent Weight : 0.000 g/eq.
Density : 0.000 g/cm3
Volume (V) : 0.001 cm3
Cycle Definition : Charge/Discharge alternance
Do not turn to OCV between techniques

Technique : 1
Chronoamperometry / Chronocoulometry
Ns                  0                   1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  14                  
Ei (V)              0.000               0.050               0.100               0.150               0.200               0.250               0.300               0.350               0.400               0.450               0.500               0.550               0.600               0.650               0.700               
vs.                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 
ti (h:m:s)          0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        
Imax                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                
unit Imax           mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  
Imin                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                
unit Imin           mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  
dQM                 0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
unit dQM            mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                
record              <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 
dI                  5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               
unit dI             uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  
dQ                  0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
unit dQ             mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                
dt (s)              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              
dta (s)             0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              
E range min (V)     -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              
E range max (V)     1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               
I Range             100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              
I Range min         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range max         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range init        Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
Bandwidth           5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   
goto Ns'            0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   
nc cycles           0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   

Technique : 2
Chronoamperometry / Chronocoulometry
Ns                  0                   1                   2                   3                   4                   5                   6                   7                   8                   9                   10                  11                  12                  13                  14                  
Ei (V)              0.700               0.650               0.600               0.550               0.500               0.450               0.400               0.350               0.300               0.250               0.200               0.150               0.100               0.050               0.000               
vs.                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 Ref                 
ti (h:m:s)          0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        0:00:30.0000        
Imax                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                
unit Imax           mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  
Imin                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                pass                
unit Imin           mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  mA                  
dQM                 0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
unit dQM            mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                
record              <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 <I>                 
dI                  5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               5.000               
unit dI             uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  uA                  
dQ                  0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               0.000               
unit dQ             mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                mA.h                
dt (s)              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              0.1000              
dta (s)             0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              0.0100              
E range min (V)     -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              -1.000              
E range max (V)     1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               1.000               
I Range             100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              100 mA              
I Range min         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range max         Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
I Range init        Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               Unset               
Bandwidth           5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   5                   
goto Ns'            0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   
nc cycles           0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   0                   
